@node Builder
@chapter Builder

@section Global environment

To turn code into an AST a @emph{global environment} is required to
associate meaning with names in the code.  We cannot use the host
environment for this purpose, because it may have different meanings
associated with names than what we need for this procedure.  As
a trivial example, the function @code{allocate-instance} in the host
system is used to allocate all standard objects.  But
@code{allocate-instance} is also a target function for allocating
objects according to the way such objects are represented by the
target system.  These two functions must be available simultaneously.

Most systems solve this problem by using temporary names for target
packages during the bootstrapping process.  For example, even though
in the final target system, the name @code{allocate-instance} must be
a symbol in the @code{common-lisp} package, during the bootstrapping
process, the name might be a symbol in a package with a different
name.

In Iconoclast we solve the problem by using a @emph{first-class global
  environment}, provided by the library Clostrum.
