iconoclast.pdf: iconoclast.texi chap-introduction.texi chap-ast-classes-for-special-forms.texi chap-ast-classes-for-standard-macro-forms.texi chap-builder.texi
	texi2pdf iconoclast.texi

clean:
	rm -f *.aux *.toc *.log iconoclast.pdf *~
