(cl:in-package #:iconoclast-builder)

(defmethod expand ((ast ico:cond-ast))
  (let ((clause-asts (ico:clause-asts ast)))
    (abp:with-builder ((make-instance 'builder))
      (if (null clause-asts)
          (abp:node* (:unparsed :expression 'nil))
          (let* ((first-clause-ast (first clause-asts))
                 (test-ast (ico:test-ast first-clause-ast))
                 (form-asts (ico:form-asts first-clause-ast))
                 (remaining-cond-ast
                   (abp:node* (:cond :clause-asts (rest clause-asts)))))
            (if (null form-asts)
                (let ((variable-name (gensym)))
                  (flet ((make-variable-ast ()
                           (abp:node* (:variable-name :name variable-name))))
                    (abp:node* (:let)
                      (1 :binding
                         (abp:node* (:value-binding)
                           (1 :name (make-variable-ast))
                           (1 :value test-ast)))
                      (1 :form
                         (abp:node* (:if)
                           (1 :test (make-variable-ast))
                           (1 :then (make-variable-ast))
                           (1 :else remaining-cond-ast))))))
                (abp:node* (:if)
                  (1 :test test-ast)
                  (1 :then (abp:node* (:progn :form-asts form-asts)))
                  (1 :else remaining-cond-ast))))))))
