(cl:in-package #:iconoclast-visualizer)

(defmethod display-ast ((ast ico:let-ast))
  (draw-ast ast "let")
  (with-indentation (40)
    (display-asts (ico:binding-asts ast)))
  (with-indentation (30)
    (display-asts (ico:declaration-asts ast)))
  (with-indentation (20)
    (display-asts (ico:form-asts ast))))

(defmethod display-ast ((ast ico:let*-ast))
  (draw-ast ast "let*")
  (with-indentation (40)
    (display-asts (ico:binding-asts ast)))
  (with-indentation (30)
    (display-asts (ico:declaration-asts ast)))
  (with-indentation (20)
    (display-asts (ico:form-asts ast))))
