(cl:in-package #:iconoclast-visualizer)

(defmethod display-ast ((ast ico:prog2-ast))
  (draw-ast ast "prog2")
  (with-indentation (60)
    (display-ast (ico:first-form-ast ast)))
  (with-indentation (40)
    (display-ast (ico:second-form-ast ast)))
  (with-indentation (20)
    (display-asts (ico:form-asts ast))))
